### ISSUE TITLE
As a user, I would like to be able to report a potential wrongdoing, so that I can raise awareness.

### ISSUE THREAD

**Issue by KasperNissen1997** [jonwangholm/Team6-Budweg#1]
# Tasks 📋

## Analyse & Design ✏️
 - [x] #2 
 - [x] #6
 - [x] #7
 - [x] #11
 - [x] #8 
 - [x] #12
 - [x] #13

## Implementation 💻
 - [x] #9
 - [x] #10
 - [ ] #14

### WPF
 - [x] #15
 - [x] #16
 - [ ] #17
 - [ ] #18

### DB
 - [x] #20
 - [x] #21

# Acceptance Criteria ✅
 - [ ] Users can report wrongdoings.
 - [ ] Users should be able to mark themselves as anonymous.

## Technical
 - [ ] The code-behind of each view contains minimal code.
 - [ ] There are no binding errors.
 - [ ] The DCD and codebase reflect each other.
 - [ ] Consistency across all of the codebase.
