### ISSUE TITLE
As a user, I would like to be able to access reports that I have sent, so that I can see the replies.

### ISSUE THREAD

**Issue by JonasHaile** [jonwangholm/Team6-Budweg#4]
# Tasks

## Analysis & Design
 - [ ] Update Domain model and Object model.
 - [ ] Create/Update use cases
 - [ ] Create/Update SSD and corresponding OC
 - [ ] Update DCD and if needed, the PD

## Implementation
 - [ ] ?

# Acceptance Criteria
- [ ] Only the user that sent the report, and the user responsible for handling reports, should be able to access the report.
