### ISSUE TITLE
As a user, I would like to be able to communicate in reports, so that I can provide more information in reports, if needed.

### ISSUE THREAD

**Issue by AdilJavatogo** [jonwangholm/Team6-Budweg#5]
# Tasks

## Analysis & Design
 - [ ] Update Domain model and Object model.
 - [ ] Create/Update use cases
 - [ ] Create/Update SSD and corresponding OC
 - [ ] Update DCD and if needed, the PD

## Implementation
 - [ ] ?

# Acceptance Criteria
- [ ] Only the sender or the user responsible for handling reports should be able to communicate within reports.
- [ ] If the report is anonymous, then all replies made by the sender should remain anonymous.
